### ISSUE TITLE
Add Technology

### ISSUE THREAD

**Issue by sylwiavargas** [sylwiavargas/The-Code-Bending-Dictionary#11]
- **migration:** 
  - Add Technology migration -> see the ERD below
  - Change Definition migration (now also belongs_to a Technology) -> see the ERD below

<img width="817" alt="ERD" src="https://user-images.githubusercontent.com/45401242/94624695-4ed84880-02b7-11eb-864d-1f9b5f5825c6.png">

- **Add Technology controller:** index action, show action
- **Add Technology routes:** index, show
- **model:** 
  - Add Technology model: validation for name, has_many definitions, has_many words through definitions
  - Update Definition model: belongs_to Technology
  - Update Word model: has_many Technologies through Definitions

- **Update seeds:** 
  - add Technology instances ("JavaScript", "React", "Rails", "Ruby", "Redux", "General Tech")
  - add correct technology key to Definition instances
- **Add Technology folder and view files:** index view file stub, show view file stub

**Comment by naoufalelh** [comment]
Can you assigne this to me as well? Thanks

**Comment by sylwiavargas** [comment]
Hi @naoufalelh ! We are just getting set up for Hacktoberfest but if you'd like to go ahead with this one already, that'd be great! Please note that I have updated the description. 

We don't have the `Contributing.md` file yet (it's being written) so, for clarity, please:
- use `dev` branch to create a branch with your name and the name of the feature
- after you're done, please make a PR to `dev` branch

If you have any questions, reach out! 
Thank you! ✨

**Comment by naoufalelh** [comment]
Hey ! thanks for the info. 
I'm also starting to contribute for Hacktoberfest (it will be my first time as I mentioned in the other issue).

**Comment by sylwiavargas** [comment]
Hi @naoufalelh ! 
Please, before you contribute, read [contributing guide](https://github.com/sylwiavargas/The-Code-Bending-Dictionary/wiki/3.-Contributing) and make sure that the [code of conduct](https://github.com/sylwiavargas/The-Code-Bending-Dictionary/wiki/2.-Code-of-Conduct) vibes well with you! 

Because I haven't assigned the dates yet (doing it now), heads up: ideally, we would have this (and the other, #12) issue ready by Mon Oct, 5th. Do you think that that's feasible?

**Comment by naoufalelh** [comment]
yeah i'm cool with that I think it can be ready by 5th of Oct. Thanks!
