### ISSUE TITLE
Add Vote

### ISSUE THREAD

**Issue by sylwiavargas** [sylwiavargas/The-Code-Bending-Dictionary#24]
**CREATE:**
- new migration to add a Votes model with the attributes below
- a Vote model with appropriate associations
  - a [method in the Vote model](https://dev.to/sylwiavargas/rails-backend-initializing-an-instance-with-a-default-value-5hb7) that makes the value attribute default to 1 if nil
- a VotesController with the following actions: new, create, edit, update, destroy
<img width="817" alt="ERD" src="https://user-images.githubusercontent.com/45401242/94624695-4ed84880-02b7-11eb-864d-1f9b5f5825c6.png">

**UPDATE:**
- seeds file by adding a few votes instances
- routes file by adding appropriate routes
- Definition and User models with appropriate associations

**Comment by GerryLarios** [comment]
Hello @sylwiavargas, Can you assign this to me? Thanks in advance :)

**Comment by sylwiavargas** [comment]
Hi @GerryLarios ! Of course — and welcome to our little contributors corner ✨
Please, before you contribute, read [contributing guide](https://github.com/sylwiavargas/The-Code-Bending-Dictionary/wiki/3.-Contributing) and make sure that the [code of conduct](https://github.com/sylwiavargas/The-Code-Bending-Dictionary/wiki/2.-Code-of-Conduct) vibes well with you! 

Because I haven't assigned the dates yet (doing it now), heads up: ideally, we would have this issue ready by Mon Oct, 5th. Do you think that that's feasible?

**Comment by GerryLarios** [comment]
Thanks :) 
I think it's feasible, and I'll work on it.
