### ISSUE TITLE
Update Gemfile ruby version currently 2.6.1 and installation guide says to use 2.7.1

### ISSUE THREAD

**Issue by naoufalelh** [sylwiavargas/The-Code-Bending-Dictionary#40]
Gemfile needs to be updated with ruby 2.7.1.

following the installation guide, when I run `bundle` I get `Your Ruby version is 2.7.1, but your Gemfile specified 2.6.1`

**Comment by sylwiavargas** [comment]
Thank you, @naoufalelh ! I have assigned you to this, if you're comfortable with it :)
