### ISSUE TITLE
Setup Rubocop for code style and quality

### ISSUE THREAD

**Issue by naoufalelh** [sylwiavargas/The-Code-Bending-Dictionary#42]
I suggest adding [Rubocop](https://github.com/rubocop-hq/rubocop) to follow Rails community style guide.

**Comment by GerryLarios** [comment]
Sure thing! @sylwiavargas can you assign me this issue to me as well? 👀

**Comment by sylwiavargas** [comment]
Thank you, @GerryLarios! I've assigned you just now ✨

**Comment by GerryLarios** [comment]
@sylwiavargas thanks! working on it!

**Comment by GerryLarios** [comment]
Working on it, planning to be ready today. @sylwiavargas
